name: project_management_system
description: A new Flutter project.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.15
  cupertino_icons: ^1.0.2
  flutter_launcher_icons:
  flutter_svg: ^2.0.4
  go_router: ^6.4.1
  fl_chart: ^0.61.0


flutter_icons:
  image_path: "assets/logo/pmsLogo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true


  assets:
    - assets/fonts/
    - assets/logo/
    - assets/
    - assets/drawer/
    - assets/img/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf