name: project_management_system
description: A new Flutter project.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.15
  cupertino_icons: ^1.0.2
  flutter_launcher_icons:
  flutter_svg: ^2.0.4
  fl_chart: ^0.61.0
  get:
  syncfusion_flutter_gauges: ^21.1.37
  analog_clock:
  smooth_page_indicator: ^1.0.1
  flutter_animation_progress_bar: ^2.3.1
  syncfusion_flutter_charts: ^21.1.39
  flutter_speed_dial:
  flutter_quill:
  file_picker:
  timeline_tile:
  flutter_expanded_tile:
  syncfusion_flutter_calendar:


flutter_icons:
  image_path: "assets/logo/pmsLogo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true


  assets:
    - assets/fonts/
    - assets/logo/
    - assets/
    - assets/drawer/
    - assets/img/
    - assets/svg/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: PT Serif
      fonts:
        - asset: assets/fonts/PTSerif-Bold.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf